# DIMACS CNF (.cnf)

# c ...      → comentariu
# p cnf V C  → V = variabile, C = clauze
# linie      → clauză
# 0          → final clauză

# c Sudoku 4x4 example
# p cnf 64 120
# 1 -2 3 0
# -1 4 0
# 5 0

def write_dimacs_cnf(filename, clauses):
    vars_set = set()

    # colectam toate variabilele
    for clause in clauses:
        for lit in clause:
            vars_set.add(abs(lit))

    num_vars = max(vars_set) if vars_set else 0
    num_clauses = len(clauses)

    with open(filename, "w") as f:
        f.write("c Generated by SAT Solver\n")
        f.write(f"p cnf {num_vars} {num_clauses}\n")

        for clause in clauses:
            line = " ".join(str(lit) for lit in clause) + " 0\n"
            f.write(line)


def read_dimacs_cnf(filename):
    clauses = []

    with open(filename, "r") as f:
        for line in f:
            line = line.strip()

            # ignoram comentarii
            if not line or line.startswith("c"):
                continue

            # ignoram header
            if line.startswith("p"):
                continue

            # citim clauza
            nums = list(map(int, line.split()))

            clause = [x for x in nums if x != 0]
            clauses.append(clause)

    return clauses